# Generated by Django 5.2.14 on 2026-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_reminder_delete_add_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='today_task',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
